[project]
name = "pyrtfpa"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "numpy>=2.2.6",
]

[dependency-groups]
dev = [
    "pytest>=8.4.0",
]
