[project]
name = "pyrtfpa"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "numpy>=2.2.6",
    "pandas>=2.2.3",
    "tk>=0.1.0",
]

[dependency-groups]
dev = [
    "pytest>=8.4.0",
]
